---
title: "Untitled"
author: "Tao"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(terra)
# install.packages("soilDB")
library(soilDB)
```

```{r}
# Methods to create a SpatVector from a file or other R object.
p <- vect( "/Users/taohuang/Downloads/jdt34/jdt34.shp"
  #"C:/Users/taohuang/Documents/Tao/ARS/Johnston_Draw/UAS_AOIs_JDT3_4.shp"
  )
p
```

```{r}
# using the soilDB package to retrieve soil Map Unit Keys (MUKEYs)
mu <- mukey.wcs( p , db = 'gSSURGO')
mu
summary(mu)
```

```{r}
# inspect
plot(mu, legend = FALSE, axes = FALSE, main = metags(mu)['description'])
# add original point, after transforming to mukey grid CRS
plot(project(p, "EPSG:5070"), add = TRUE, pch = 16)
```

```{r}
b <- buffer(p, 1)
mu <- mukey.wcs(b, db = "gSSURGO") #"STATSGO") # "gNATSGO") #'gSSURGO')
# inspect
plot(mu, legend = FALSE, axes = FALSE, main = metags(mu)['description'])

# add buffer, after transforming to mukey grid CRS
plot(project(b, "EPSG:5070"), add = TRUE)

# add original point, after transforming to mukey grid CRS
plot(project(p, "EPSG:5070"), add = TRUE, pch = 16)
```

```{r}
# extract RAT for thematic mapping
rat <- cats(mu)[[1]]

# variables of interest
vars <- c("taxclname",  "drainagecl", "hydgrp" , "	taxorder", "taxsuborder")# c("dbthirdbar_r", "awc_r", "ph1to1h2o_r") #, "taxclname") #, "drainagecl")

# get / aggregate specific horizon-level properties from SDA
# be sure to see the manual page for this function
tab <- get_SDA_property(property = vars,
                        method = "Dominant Component (Category)",
                     #   method = "Dominant Component (Numeric)", 
                        mukeys = as.integer(rat$mukey),
                    #    top_depth = 0,
               #         bottom_depth = 25
                    )
tab
```

```{r}
tab_num <- get_SDA_property(property =  c("silttotal_r" ,"sandtotal_r", "claytotal_r", "om_r"), # , "sandvc_r", "sandvf_r",   "dbtenthbar_r","sandvf_h", "sandvf_l"),
                        
                        

                        method = "Dominant Component (Numeric)", 
                        mukeys = as.integer(rat$mukey),
                    #    top_depth = 0,
               #         bottom_depth = 25
                    )
tab_num
```

```{r}
library(soiltexture)
TT.plot( class.sys = "USDA.TT" )
```

```{r}
# Create a dummy data frame of soil textures:
my.text <- data.frame( 
    "CLAY"  = c(05,60,15,05,25,05,25,45,65,75,13,47), 
    "SILT"  = c(05,08,15,25,55,85,65,45,15,15,17,43), 
    "SAND"  = c(90,32,70,70,20,10,10,10,20,10,70,10), 
    "OC"    = c(20,14,15,05,12,15,07,21,25,30,05,28)  
)   #

# Display the table:
my.text

# Classify according to the HYPRES / European Soil Map classification
TT.points.in.classes( 
    tri.data    = my.text[1:5,], 
    class.sys   = "HYPRES.TT"  
)   #

# Classify according to the USDA classification
TT.points.in.classes( 
    tri.data    = my.text[1:5,], 
    class.sys   = "USDA.TT"  
)   #
```

```{r}
my.text <- data.frame( 
    "CLAY"  = tab_num$claytotal_r , 
    "SILT"  =  tab_num$silttotal_r , 
    "SAND"  = tab_num$sandtotal_r , 
    "OC"    =  tab_num$om_r 
)   #

# Display the table:
my.text



# Classify according to the USDA classification
TT.points.in.classes( 
    tri.data    = my.text , 
    class.sys   = "USDA.TT"  
)
```

```{r}
1 Cl
2 SiCl
3 SaCl
4 ClLo
5 SiClLo
6 SaClLo
7 Lo
8 SiLo
9 SaLo
10 Si
11 LoSa
12 Sa
1 clay
2 silty clay
3 sandy clay
4 clay loam
5 silty clay loam 
6 sandy clay loam 
7 loam
8 silty loam 
9 sandy loam
10 silt
11 loamy sand 
12 sand

```

